added command-line flag --utcc for compiling with TinyCC and linking against uClibc

diff --git a/minicc b/minicc
--- a/minicc
+++ b/minicc
@@ -29,10 +29,12 @@ GCC=gcc
 TCC=
 TCCLD=
 DO_ADD_LIB=1
+DO_ADD_INCLUDEDIR=1
 DO_LINK=1
 HAD_OFLAG=
 HAD_V=
 ARCH=i686
+USE_UCLIBC=
 
 SKIPARG=
 APPENDARG=
@@ -54,6 +56,8 @@ for ARG in "$@"; do
    --gcc=*) TCC=; GCC="${ARG#*=}" ;;
    --tcc) GCC=; TCC="$MYDIR"/tools/pts-tcc ;;
    --tcc=*) GCC=; TCC="${ARG#*=}" ;;
+   --utcc) GCC=; TCC="$MYDIR"/tools/pts-tcc; USE_UCLIBC=1 ;;
+   --utcc=*) GCC=; TCC="${ARG#*=}"; USE_UCLIBC=1 ;;
    --tccld) TCCLD="$MYDIR"/tools/pts-tcc ;;
    --tccld=*) TCCLD="${ARG#*=}" ;;
    -static | -m32 | -fno-pic | -fpic | -fno-pie | -pie | -no-pie | -flto | -fno-lto | -nostartfiles) ;;
@@ -63,6 +67,7 @@ for ARG in "$@"; do
    -[DUI]*?) ARGS="$ARGS$NL$ARG" ;;
    -O*) ARGS="$ARGS$NL$ARG"; HAD_OFLAG=1 ;;
    -nostdlib | -nodefaultlibs) DO_ADD_LIB= ;;
+   -nostdinc) DO_ADD_INCLUDEDIR= ;;
    -[cSE]) ARGS="$ARGS$NL$ARG"; DO_ADD_LIB=; DO_LINK= ;;
    -s) ARGS="$ARGS$NL$ARG" ;;
    -v) HAD_V=1; ARGS="$ARGS$NL$ARG" ;;
@@ -89,8 +94,21 @@ if test "$TCC" && test "$GCC"; then
   echo "fatal: conflicting compilers, both --tcc=... and --gcc=..." >&2
   exit 1
 fi
-if ! test "$TCC" && test ! "$GCC"; then
+if test -z "$TCC" && test -z "$GCC"; then
   echo "fatal: missing compiler, neither --tcc=... nor --gcc=..." >&2
+  exit 1
+fi
+if test "$USE_UCLIBC" && test "$DO_ADD_LIB" && test "${TCC%/pts-tcc}" = "$TCC"; then
+  # That's because ///tmp///LIBTCC1.a is embedded in the tools/pts-tcc executable.
+  # TODO(pts): Extract it.
+  echo "fatal: currently uClibc needs pts-tcc" >&2
+  exit 1
+fi
+if test "$USE_UBLIBC" && test "$ARCH" = i386; then
+  # In fact, it was compiled for -march=pentium3, which is newer than
+  # -march=i686.
+  # TODO(pts): Recompile at least parts of it for -march=i686.
+  echo "fatal: the bundled uClibc doesn't work on i386" >&2
   exit 1
 fi
 
@@ -121,22 +139,49 @@ if test -z "$HAD_OFLAG"; then  # Add some size-optimizing flags.
   esac
   test "$TCC" && OFLAG_ARGS="-Os"
 fi
-
-# The `-B$MYDIR/gcctooldir' argument makes our gcctooldir/collect2 or gcctooldir/ld run.
-ARGS="$TCC$NL$GCC$NL-B$MYDIR/gcctooldir$NL-m32$NL-march=$ARCH$NL-static$NL-fno-pic$NL-U_FORTIFY_SOURCE$NL-fno-stack-protector$NL-fno-unwind-tables$NL-fno-asynchronous-unwind-tables$NL-fno-builtin$NL-fno-ident$NL-fsigned-char$NL-ffreestanding$NL-fno-lto$NL-nostdlib$NL-nostdinc$NL-I$MYDIR/include$NL$OFLAG_ARGS$NL$ARGS"
+INCLUDEDIR_ARG=
+DEF_ARG=
+if test "$DO_ADD_INCLUDEDIR"; then
+  INCLUDEDIR_ARG="-I$MYDIR/include"
+  test "$USE_UCLIBC" && DEF_ARG="-D__asm__(x)=$NL-D__UCLIBC__"   # Make it ignore __asm__("mini_printf") in stdio.h, so that the linker will find the uClibc printf(...).
+fi
+if test "$TCC"; then
+  # TODO(pts): Does TCC really generate i386-only code?
+  ARGS="$TCC$NL-m32$NL-march=$ARCH$NL-static$NL-nostdlib$NL-nostdinc$NL$OFLAG_ARGS$NL$DEF_ARG$NL$ARGS$NL$INCLUDEDIR_ARG"
+else
+  # This also works with TCC, but it's too much cruft.
+  # The `-B$MYDIR/gcctooldir' argument makes our gcctooldir/collect2 or gcctooldir/ld run.
+  # Add $INCLUDEDIR_ARG last, so that -I... specified by the user takes precedence.
+  ARGS="$TCC$NL$GCC$NL-B$MYDIR/gcctooldir$NL-m32$NL-march=$ARCH$NL-static$NL-fno-pic$NL-U_FORTIFY_SOURCE$NL-fno-stack-protector$NL-fno-unwind-tables$NL-fno-asynchronous-unwind-tables$NL-fno-builtin$NL-fno-ident$NL-fsigned-char$NL-ffreestanding$NL-fno-lto$NL-nostdlib$NL-nostdinc$NL$OFLAG_ARGS$NL$DEF_ARG$NL$ARGS$NL$INCLUDEDIR_ARG"
+fi
 if test "$DO_ADD_LIB"; then
-  LIBFN="$MYDIR/libmin$ARCH.a"
-  if ! test -f "$LIBFN"; then
-    if ! "$MYDIR/build.sh" !| test -f "$LIBFN"; then
-      echo "fatal: failed to build libc .a: $LIBFN" >&2
-      exit 3
+  if test "$USE_UCLIBC"; then
+    LIBFN=///tmp///LIBTCC1.a  # Embedded in tools/pts-tcc.
+  else
+    LIBFN="$MYDIR/libmin$ARCH.a"
+    if ! test -f "$LIBFN"; then
+      if "$MYDIR/build.sh" && test -f "$LIBFN"; then :; else
+        echo "fatal: failed to build libc .a: $LIBFN" >&2
+        exit 3
+      fi
     fi
   fi
   if test "$TCC" || test "$TCCLD"; then  # TCC needs an explicit start*.o in the command line -- or does it?
     OBJFN="$MYDIR/need_start.o"
     if ! test -f "$OBJFN"; then
-      echo "fatal: missing libc start .o: $OBJFN" >&2
+      echo "fatal: missing libc need-start .o: $OBJFN" >&2
       exit 3
+    fi
+    ARGS="$ARGS$NL$OBJFN"
+  fi
+  if test "$USE_UCLIBC"; then
+    OBJFN="$MYDIR/start_uclibc_linux.o"
+    if ! test -f "$OBJFN"; then
+      test "$HAD_V" && echo "info: compiling: $MYDIR/start_uclibc_linux.nasm" >&2
+      if "$MYDIR/tools/nasm-0.98.39" -O0 -w+orphan-labels -f elf -o "$OBJFN" "$MYDIR/start_uclibc_linux.nasm" && test -f "$OBJFN"; then :; else
+        echo "fatal: failed to build uclibc start .o: $OBJFN" >&2
+        exit 3
+      fi
     fi
     ARGS="$ARGS$NL$OBJFN"
   fi
