added smart linking (`minicc -msmart', enabled by default)

diff --git a/gcctooldir/ld b/gcctooldir/ld
--- a/gcctooldir/ld
+++ b/gcctooldir/ld
@@ -10,7 +10,9 @@ if test "$MINICC_TCCLD"; then
   # TCC accepts all these flags (and ignores -m elf_i386).
   ARGS="${MINICC_TCCLD:-ld}$NL-nostdlib$NL-m${NL}elf_i386$NL-static"
 else
-  ARGS="${MINICC_LD:-ld}$NL-nostdlib$NL-m${NL}elf_i386$NL-static$NL-z${NL}norelro"
+  # `-e _start' is needed, because without it GNU gold(1) wouldn't fail to link if _start is not defined.
+  # `--fatal-warnings' is needed, because without it GNU ld(1) would happily create an executable without _start.
+  ARGS="${MINICC_LD:-ld}$NL-nostdlib$NL-m${NL}elf_i386$NL-static$NL-z${NL}norelro$NL-e${NL}_start$NL--fatal-warnings"
 fi
 test "$MINICC_LDV" && ARGS="$ARGS$NL-v" && MINICC_LDV=-v
 
@@ -19,6 +21,8 @@ SKIPARG=
 APPENDARG=
 DO_STRIP=
 OUTFILE=a.out
+SMART_ARCH=
+SMART_LIBCD=
 
 for ARG in "$@"; do
   if test "$SKIPARG"; then
@@ -37,6 +41,8 @@ for ARG in "$@"; do
    --hash-style=*) ;;  # --hash-style=gnu
    --sysroot=*) ;;  # --sysroot=/
    --as-needed) ;;
+   --smart-arch=?*) SMART_ARCH="${ARG#*=}" ;;
+   --smart-libcd=?*) SMART_LIBCD="${ARG#*=}" ;;
    -static) ;;
    -sss) DO_STRIP=1 ;;  # Strip all symbols and even more (tools/elfxfix). `-s' is already added to args.
    -s) ARGS="$ARGS$NL$ARG" ;;  # Strip all symbols.
@@ -45,7 +51,7 @@ for ARG in "$@"; do
    -z) SKIPARG=1 ;;  # -z relro. TODO(pts): Make `-z execstack' and `-z noexecstack' go through.
    -m) SKIPARG=1 ;;  # -m elf_i386.
    -o) APPENDARG="$ARG" ;;
-   -e) APPENDARG="$ARG" ;;  # -e _start (implicit).
+   #-e) APPENDARG="$ARG" ;;  # -e _start (implicit).  With smart linking, we don't support overriding it.
    -[Nv]) ARGS="$ARGS$NL$ARG" ;;
    -*) echo "fatal: unsupported hooked ld flag: $ARG" >&2; exit 1 ;;
    *.a | *.o)
@@ -75,6 +81,53 @@ for ARG in $LDTMPOARGS; do
 done
 
 test "$MINICC_LDV" && echo "info: running linker:" $ARGS >&2
+if test "$SMART_ARCH" && test "$SMART_LIBCD"; then
+  HAD_V="$MINICC_LDV"
+  SMART_TOOLS="$MINICC_TOOLS"
+  DO_SMART=1
+  # This code contains duplication with the $TCC $DO_SMART code in minicc.
+  test "${OUTFILE#-}" = "$OUTFILE" || MYDIR="./$OUTFILE"
+  $ARGS 2>"$OUTFILE.err" >&2; EC="$?"
+  if test "$EC" = 0; then
+    cat "$OUTFILE.err"
+    rm -f "$OUTFILE.err"
+    exit
+  fi
+  # The regexps below work for $TCCLD, ld of $GCC, ld of $GCC (Binutils), gold of $GCC (Binutils). TODO(pts): Make it work with lld (Clang).
+  # Examples for GNU ld(1) and GNU gold(1):
+  # : warning: cannot find entry symbol '_start'
+  # : warning: cannot find entry symbol _start; defaulting to 0000000008048074
+  # : warning: entry symbol '_start' exists but is not defined
+  UNDEFSYMS="$(awk '{if((((/: undefined reference to [`'\''].+'\''$/&&sub(/^.*?: undefined reference to [`'\'']/, "")||sub(/^tcc: error: undefined symbol '\''/,""))&&sub(/'\''$/,""))||(/: warning: /&&sub(/^.*: warning: (cannot find )?entry symbol '\''?/,"")&&sub(/['\'';].*/,"")&&!/ /))&&!h[$0]){h[$0]=1;printf"%s%s",c,$0;c=","}}' <"$OUTFILE.err")"
+  if test -z "$UNDEFSYMS"; then
+    cat "$OUTFILE.err"
+    rm -f "$OUTFILE.err"
+    exit "$EC"  # No undefined symbols found, this means there is another reason for the $TCC failure.
+  fi
+  rm -f "$OUTFILE.err" "$OUTFILE.smart.o"
+  NASMARCHARG=
+  test "$SMART_ARCH" = i686 || NASMARCHARG=-DCONFIG_I386
+  DEF_ARG=
+  for F in $(cat "$SMART_LIBCD/libc.defs"); do  # Split on any whitespace, $IFS hasn't been set yet.
+    DEF_ARG="$DEF_ARG$NL$F"
+  done
+  NASMCMD="$SMART_TOOLS/nasm-0.98.39$NL-O0$NL-w+orphan-labels$NL-f${NL}elf$NL$NASMARCHARG$NL-DUNDEFSYMS=$UNDEFSYMS$NL$DEF_ARG$NL-o$NL$OUTFILE.smart.o$NL$SMART_LIBCD/smart.nasm"; EC="$?"
+  test "$HAD_V" && echo "info: running smart nasm:" $NASMCMD >&2
+  $NASMCMD; EC="$?"
+  if test "$EC" = 0 && test -f "$OUTFILE.smart.o"; then :; else
+    rm -f "$OUTFILE.smart.o"
+    test "$EC" = 0 && EC=1
+    exit "$EC"
+  fi
+  # /usr/bin/objdump -d "$OUTFILE.smart.o"
+  ARGS="$ARGS$NL$OUTFILE.smart.o$NL$SMART_LIBCD/libc.$SMART_ARCH.a"
+  test "$HAD_V" && echo "info: running linker:" $ARGS >&2  # GCC also writes to stderr.
+  if test -z "$DO_STRIP"; then
+    $ARGS >&2; EC="$?"
+    rm -f "$OUTFILE.smart.o"
+    exit "$EC"
+  fi
+fi
 if test "$DO_STRIP"; then
   $ARGS >&2 || exit "$?"
   FIX_O_FN=
@@ -91,6 +144,7 @@ if test "$DO_STRIP"; then
     $EFARGS >&2; EC="$?"
     if test "$EC" != 0; then
       rm -f -- "$FIX_O_FN"
+      test "$DO_SMART" && rm -f "$OUTFILE.smart.o"
       exit "$EC"
     fi
     if test -f "$FIX_O_FN"; then  # elfxfix has created it.
@@ -105,8 +159,10 @@ if test "$DO_STRIP"; then
       fi
     fi
     rm -f -- "$FIX_O_FN"
+    test "$DO_SMART" && rm -f "$OUTFILE.smart.o"
     exit "$EC"
   fi
+  test "$DO_SMART" && rm -f "$OUTFILE.smart.o"
   ARGS="$EFARGS"
 fi
 exec $ARGS >&2  # We need 2 to redirect stdout to stderr of GNU `ld -v'.
diff --git a/minicc b/minicc
--- a/minicc
+++ b/minicc
@@ -65,6 +65,7 @@ ARCH=i686
 USE_UTCC=
 GCC_BARG=-pipe  # Harmless default.
 LIBC=
+DO_SMART=
 
 case "$1" in
  "" | -* | *.[aocisS]) ;;  # A flag or a source file name is not a program name.
@@ -114,6 +115,8 @@ for ARG in "$@"; do
    -static | -m32 | -fno-pic | -fpic | -fno-pie | -pie | -no-pie | -flto | -fno-lto | -nostartfiles) ;;
    -march=i[36]86) ARCH="${ARG#*=}" ;;
    -march=*) echo "fatal: unsupported minicc arch flag: $ARG" >&2; exit 1 ;;
+   -msmart) DO_SMART=1 ;;  # Enable smart linking.
+   -mno-smart) DO_SMART=0 ;;
    -Wno-no) WFLAGS= ;;  # Disable warnings. GCC and Clang accept and ignore it.
    -W*) ARGS="$ARGS$NL$ARG"; WFLAGS= ;;
    -[fm]*) ARGS="$ARGS$NL$ARG" ;;
@@ -138,6 +141,8 @@ for ARG in "$@"; do
    *) echo "fatal: unsupported input file extension: $ARG" >&2; exit 1 ;;
   esac
 done
+
+test "$DO_ADD_LIB" || DO_SMART=0
 
 NEED_LIBC=
 test "$DO_ADD_INCLUDEDIR" && NEED_LIBC=1
@@ -270,6 +275,7 @@ if test "$DO_ADD_INCLUDEDIR"; then
     DEF_ARG="-D__asm__(x)=$NL-D__UCLIBC__"   # Make it ignore __asm__("mini_printf") in stdio.h, so that the linker will find the uClibc printf(...).
   else
     # TODO(pts): Ignore comments in lines starting with `#'.
+    # This DEF_ARG must be valid for for nasm (for -msmart), do it should be contain only `-D...' and `-U...'.
     for F in $(cat "$MYDIR/libc/$LIBC/libc.defs"); do  # Split on any whitespace, $IFS hasn't been set yet.
       DEF_ARG="$DEF_ARG$NL$F"
     done
@@ -291,6 +297,10 @@ if test "$DO_ADD_LIB"; then
   if test "$USE_UTCC"; then
     test "$GCC" && LIBWL=-Wl,  # -Wl, is needed, otherwise GCC will complain that it is not able to find "$LIBFN" (which doesn't exist on the filesystem).
     LIBFN=///tmp///LIBTCC1.a  # Embedded in tools/pts-tcc.
+    if test "$DO_SMART" && test "$DO_SMART" != 0; then
+      echo "fatal: --utcc doesn't support -msmart" >&2
+      exit 3
+    fi
   else
     LIBFN="$MYDIR/libc/$LIBC/libc.$ARCH.a"
     if ! test -f "$LIBFN"; then
@@ -309,7 +319,17 @@ if test "$DO_ADD_LIB"; then
         fi
       fi
     fi
+    if test -z "$DO_SMART"; then
+      DO_SMART=0
+      test -f "$MYDIR/libc/$LIBC/smart.nasm" && DO_SMART=1  # Use smart linking by default if available for libc.
+    elif test "$DO_SMART" != 0; then
+      if ! test -f "$MYDIR/libc/$LIBC/smart.nasm"; then
+        echo "fatal: missing libc smart.nasm for -msmart: $MYDIR/libc/$LIBC/smart.nasm" >&2
+        exit 3
+      fi
+    fi
   fi
+  test "$DO_SMART" || DO_SMART=0  # Fallback.
   if test "$TCC" || test "$TCCLD"; then  # TCC needs an explicit start*.o in the command line -- or does it?
     OBJFN="$MYDIR/helper_lib/need_start.o"
     if ! test -f "$OBJFN"; then
@@ -334,7 +354,7 @@ if test "$DO_ADD_LIB"; then
       ARGS="$ARGS$NL$OBJFN"
     fi
   fi
-  ARGS="$ARGS$NL$LIBWL$LIBFN"
+  test "$DO_SMART" = 0 && ARGS="$ARGS$NL$LIBWL$LIBFN"
   if test "$TCC" && test -z "$USE_UTCC"; then
     LIBFN="$MYDIR/helper_lib/libminitcc1.a"
     if ! test -f "$LIBFN"; then
@@ -343,7 +363,7 @@ if test "$DO_ADD_LIB"; then
         exit 3
       fi
     fi
-    ARGS="$ARGS$NL$LIBFN"
+    test "$DO_SMART" = 0 && ARGS="$ARGS$NL$LIBFN"
   fi
   if test "$USE_UTCC"; then
     # OBJFN="$MYDIR/helper_lib/start_uclibc_linux.o"  # Not needed.
@@ -351,6 +371,7 @@ if test "$DO_ADD_LIB"; then
     ARGS="$ARGS$NL$LIBWL$OBJFN"
   fi
 fi
+test "$DO_SMART" || DO_SMART=0  # Fallback.
 
 test "$TMPDIR" || TMPDIR=/tmp
 if test "${TMPDIR#/}" = "$TMPDIR"; then TMPDIR=".//////$TMPDIR"
@@ -362,14 +383,59 @@ export TMPDIR
 
 IFS="$NL"  # Argument splitting will happen over newlines only.
 export MINICC_TOOLS="$MYDIR/tools"
-test "$HAD_V" && echo "info: running compiler:" $ARGS >&2  # !! TODO(pts): Write to stdout if GCC also writes there.
-if test "$TCC" && test "$DO_LINK" && test "$DO_STRIP"; then
-  $ARGS || exit "$?"
-  # Same functionality as in gcctooldir/ld.
-  MINICC_LDV=
-  test "$HAD_V" && MINICC_LDV=-v
-  EFARGS="$MINICC_TOOLS/elfxfix$NL-l$NL-a$NL-s$NL$MINICC_LDV$NL--$NL$OUTFILE"
-  test "$MINICC_LDV" && echo "info: running extra strip:" $EFARGS >&2
-  ARGS="$EFARGS"
+test "$HAD_V" && echo "info: running compiler:" $ARGS >&2  # GCC also writes to stderr.
+if test "$TCC"; then
+  if test "$DO_SMART" != 0; then  # Smart linking with $TCC.
+    SMART_LIBCD="$MYDIR/libc/$LIBC"
+    SMART_TOOLS="$MYDIR/tools"
+    SMART_ARCH="$ARCH"
+    # This code contains duplication with the $SMART_LIBCD code in gcctooldir/ld.
+    test "${OUTFILE#-}" = "$OUTFILE" || MYDIR="./$OUTFILE"
+    $ARGS "$MYDIR/helper_lib/libminitcc1.a" 2>"$OUTFILE.err"; EC="$?"  # TODO(pts): Write a C program to extract undefined references and display errors in a streaming way. (Some errors like `In ...' need to be buffered.)
+    if test "$EC" = 0; then
+      cat "$OUTFILE.err"
+      rm -f "$OUTFILE.err"
+      exit
+    fi
+    # The regexps below work for $TCCLD, ld of $GCC, ld of $GCC (Binutils), gold of $GCC (Binutils). TODO(pts): Make it work with lld (Clang).
+    UNDEFSYMS="$(awk '{if((/: undefined reference to [`'\''].+'\''$/&&sub(/^.*?: undefined reference to [`'\'']/, "")||sub(/^tcc: error: undefined symbol '\''/,""))&&sub(/'\''$/,"")&&!h[$0]){h[$0]=1;printf"%s%s",c,$0;c=","}}' <"$OUTFILE.err")"
+    if test -z "$UNDEFSYMS"; then
+      cat "$OUTFILE.err"
+      rm -f "$OUTFILE.err"
+      exit "$EC"  # No undefined symbols found, this means there is another reason for the $TCC failure.
+    fi
+    rm -f "$OUTFILE.err" "$OUTFILE.smart.o"
+    NASMARCHARG=
+    test "$SMART_ARCH" = i686 || NASMARCHARG=-DCONFIG_I386
+    DEF_ARG=
+    for F in $(cat "$SMART_LIBCD/libc.defs"); do  # Split on any whitespace, $IFS hasn't been set yet.
+      DEF_ARG="$DEF_ARG$NL$F"
+    done
+    NASMCMD="$SMART_TOOLS/nasm-0.98.39$NL-O0$NL-w+orphan-labels$NL-f${NL}elf$NL$NASMARCHARG$NL-DUNDEFSYMS=$UNDEFSYMS$NL$DEF_ARG$NL-o$NL$OUTFILE.smart.o$NL$SMART_LIBCD/smart.nasm"; EC="$?"
+    test "$HAD_V" && echo "info: running smart nasm:" $NASMCMD >&2
+    $NASMCMD; EC="$?"
+    if test "$EC" = 0 && test -f "$OUTFILE.smart.o"; then :; else
+      rm -f "$OUTFILE.smart.o"
+      test "$EC" = 0 && EC=1
+      exit "$EC"
+    fi
+    # /usr/bin/nm "$OUTFILE.smart.o"
+    ARGS="$ARGS$NL$OUTFILE.smart.o$NL$SMART_LIBCD/libc.$SMART_ARCH.a$NL$MYDIR/helper_lib/libminitcc1.a"
+    test "$HAD_V" && echo "info: running compiler:" $ARGS >&2  # GCC also writes to stderr.
+    $ARGS; EC="$?"
+    rm -f "$OUTFILE.smart.o"
+    exit "$EC"
+  fi
+  if test "$DO_LINK" && test "$DO_STRIP"; then
+    $ARGS || exit "$?"
+    # Same functionality as in gcctooldir/ld.
+    MINICC_LDV=
+    test "$HAD_V" && MINICC_LDV=-v
+    EFARGS="$MINICC_TOOLS/elfxfix$NL-l$NL-a$NL-s$NL$MINICC_LDV$NL--$NL$OUTFILE"
+    test "$MINICC_LDV" && echo "info: running extra strip:" $EFARGS >&2
+    ARGS="$EFARGS"
+  fi
+elif test "$DO_SMART" != 0; then  # Smart linking with $GCC.
+  ARGS="$ARGS$NL-Wl,--smart-arch=$ARCH$NL-Wl,--smart-libcd=$MYDIR/libc/$LIBC"
 fi
 exec $ARGS
